import = ["dracula.toml"]

[shell]
program = "/usr/local/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "SauceCodePro Nerd Font Propo"
size = 13
