local o = vim.opt

o.number         = true -- enable line number
o.relativenumber = true -- enable relative line number
o.undofile       = true -- persistent undo
o.cursorline     = true -- enable cursor line
o.expandtab      = true -- use spaces instead of tabs
o.hidden         = true -- keep hidden buffers
o.autoindent     = true -- enable autoindent
o.smarttab       = true -- make tab behaviour smarter
o.splitbelow     = true -- split below instead of above
o.splitright     = true -- split right instead of left
o.splitkeep      = "screen" -- stabilize split
o.swapfile       = false -- disable swapfile
o.wrap           = false -- don't wrap lines
o.swapfile       = false -- disable swap
o.encoding       = "UTF-8" -- set encoding
o.shell          = "/usr/bin/bash" -- use bash instead of zsh
o.scrolloff      = 2 -- make scrolling better
o.sidescroll     = 2 -- make scrolling better
o.shiftwidth     = 2 -- set indentation width
o.sidescrolloff  = 15 -- make scrolling better
o.tabstop        = 2 -- tabsize
